[workspace]

resolver = "2"

members = [ "R401-voting-machine", "concurrency", "exquisite_corpse", "network_services", "options_and_results", "ownership", "port_scanner", "rustlings", "v010_spaghetti", "v020_configuration", "v021_app_builder","v030_domain","v040_memory","v041_file"
]
